"""sync_all_tables

Revision ID: 262ad8dd9d59
Revises: 1a2b3c4d5e6f
Create Date: 2026-05-02 02:09:17.968748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262ad8dd9d59'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_assessment_sessions_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessment_sessions_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
